# Generated by Django 5.2.6 on 2025-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('coin_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('exchange_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(default='paystack', max_length=50)),
                ('paystack_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tradewisecoin',
            name='buy_price_usd',
            field=models.DecimalField(decimal_places=6, default=0.1, max_digits=10),
        ),
        migrations.AddField(
            model_name='tradewisecoin',
            name='sell_price_usd',
            field=models.DecimalField(decimal_places=6, default=0.09, max_digits=10),
        ),
    ]
