# Generated by Django 5.2.6 on 2025-12-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cointransaction_tradewisecoin_buy_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradewisecoin',
            name='buy_price_usd',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradewisecoin',
            name='sell_price_usd',
            field=models.DecimalField(decimal_places=2, default=0.09, max_digits=10),
        ),
        migrations.CreateModel(
            name='CoinTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('coin_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('usd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('action', models.CharField(help_text="Action performed, e.g., 'Buy Approved', 'Sell Processed'", max_length=100)),
                ('performed_by', models.CharField(blank=True, help_text='Who performed the action (admin username)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='myapp.cointransaction')),
            ],
            options={
                'verbose_name': 'Coin Transaction Log',
                'verbose_name_plural': 'Coin Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
