# Generated by Django 5.2.6 on 2025-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_tradewisecoin_buy_price_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_per_referral', models.IntegerField(default=50, help_text='Number of coins awarded per successful referral')),
                ('min_payout_coins', models.IntegerField(default=50, help_text='Minimum coins required for payout')),
                ('coin_value_kes', models.DecimalField(decimal_places=2, default=10.0, help_text='Value of 1 coin in KES', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
    ]
