# Generated by Django 5.2.6 on 2025-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_referralsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCoinSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_per_referral', models.IntegerField(default=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Coin Setting',
                'verbose_name_plural': 'Referral Coin Setting',
            },
        ),
        migrations.DeleteModel(
            name='ReferralSettings',
        ),
    ]
